version: "3.4"
services:
  jupyter:
    hostname: '${DOCKER_USER}-docker'
    container_name: ${DOCKER_USER}_server
    image: lab
    volumes: 
      - ${DOCKER_HOME}:/root
    working_dir: /root/lab
    environment: 
      - PATH=/root/.pyenv/versions/lab/bin:$PATH
    ports: 
      - ${PORT}:8888
    entrypoint: zsh -c 'jupyter lab --no-browser --allow-root'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
            driver: nvidia