version: "3.4"
services:
  jupyter:
    hostname: "${DOCKER_USER}-docker"
    container_name: ${DOCKER_USER}_server
    image: lab
    volumes:
      - ${DOCKER_HOME}:/root
    working_dir: /root
    ports:
      - ${JUPYTER_PORT}:8888
    command: zsh -c '/root/.pyenv/versions/lab/bin/jupyter lab --allow-root'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
