version: "3.4"
services:
  jupyter:
    container_name: ${USER}_server
    image: lab
    volumes: 
      - ./docker-home:/root
    environment: 
      - PATH=/root/.pyenv/versions/lab/bin:$PATH
    ports: 
      - ${PORT}:8888
    entrypoint: zsh -c 'jupyter lab --no-browser --allow-root'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
            driver: nvidia
  zsh:
    image: lab
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes: 
      - ./docker-home:/root
    ports: 
      - ${PORT}:8888
    command: zsh
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
            driver: nvidia
