version: "3.4"
services:
  jupyter:
    hostname: "${USER}-lab"
    container_name: ${USER}_lab
    image: lab
    volumes:
      - ${PWD}/docker-home:/home/${USER}
      # source_folder:container_folder
    working_dir: /home/${USER}
    ports:
      - ${JUPYTER_PORT}:8888
    command: zsh -c '/home/${USER}/.pyenv/versions/lab/bin/jupyter lab --allow-root'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
